import type { Category } from "@/features/catalog/types";
import type { Listing, ListingSeller } from "@/features/listings/types";

/**
 * Placeholder catalogue + listings so every screen renders real-looking
 * content before the `catalog`/`listings`/`search` API modules (SRS Â§8.1)
 * exist. Swap `getListings`/`getListingById` for `GET /listings` calls
 * once the backend is live â€” callers already treat these as async.
 */

export const categories: Category[] = [
  {
    id: "cat-phones",
    slug: "phones-tablets",
    nameEn: "Phones & Tablets",
    nameAm: "áˆµáˆáŠ­ áŠ¥áŠ“ á‰³á‰¥áˆŒá‰µ",
    icon: "ðŸ“±",
    imageUrl: "/phone/Screenshot 2026-09-06 222848.png",
    listingCount: 1240,
  },
  {
    id: "cat-electronics",
    slug: "electronics",
    nameEn: "Electronics",
    nameAm: "áŠ¤áˆŒáŠ­á‰µáˆ®áŠ’áŠ­áˆµ",
    icon: "ðŸ–¥ï¸",
    imageUrl: "/elecronics/Screenshot 2026-09-06 222355.png",
    listingCount: 860,
  },
  {
    id: "cat-vehicles",
    slug: "vehicles",
    nameEn: "Vehicles",
    nameAm: "á‰°áˆ½áŠ¨áˆ­áŠ«áˆªá‹Žá‰½",
    icon: "ðŸš—",
    imageUrl: "/vehicle/Screenshot 2026-09-06 153515.png",
    listingCount: 410,
  },
  {
    id: "cat-furniture",
    slug: "furniture",
    nameEn: "Furniture",
    nameAm: "á‹¨á‰¤á‰µ á‹•á‰ƒ",
    icon: "ðŸ›‹ï¸",
    imageUrl: "/Ferniture/Screenshot 2026-09-06 223820.png",
    listingCount: 690,
  },
  {
    id: "cat-fashion",
    slug: "fashion",
    nameEn: "Fashion",
    nameAm: "áˆá‰¥áˆµ áŠ¥áŠ“ áŒ«áˆ›",
    icon: "ðŸ‘—",
    imageUrl: "/cloth and shhse/Screenshot 2026-09-06 221648.png",
    listingCount: 1530,
  },
  {
    id: "cat-kids",
    slug: "kids-baby",
    nameEn: "Kids & Baby",
    nameAm: "áˆáŒ†á‰½ áŠ¥áŠ“ áˆ…áŒ»áŠ“á‰µ",
    icon: "ðŸ§¸",
    imageUrl: "/kids/Screenshot 2026-09-06 223530.png",
    listingCount: 275,
  },
];

const sellers: ListingSeller[] = [
  {
    id: "seller-1",
    handle: "biniam-t",
    displayName: "Biniam T.",
    avatarUrl: "https://i.pravatar.cc/120?img=12",
    city: "Addis Ababa",
    subcity: "Bole",
    ratingAvg: 4.8,
    ratingCount: 63,
    responseRate: 96,
    responseTime: "within an hour",
    memberSince: "2024-03-01",
    isVerified: true,
    isPremium: true,
  },
  {
    id: "seller-2",
    handle: "selam-g",
    displayName: "Selam G.",
    avatarUrl: "https://i.pravatar.cc/120?img=32",
    city: "Addis Ababa",
    subcity: "Yeka",
    ratingAvg: 4.6,
    ratingCount: 28,
    responseRate: 88,
    responseTime: "within a few hours",
    memberSince: "2025-01-14",
    isVerified: true,
  },
  {
    id: "seller-3",
    handle: "yosef-m",
    displayName: "Yosef M.",
    city: "Adama",
    subcity: "Adama Ketema",
    ratingAvg: 4.2,
    ratingCount: 11,
    responseRate: 71,
    responseTime: "within a day",
    memberSince: "2025-06-20",
  },
  {
    id: "seller-4",
    handle: "hanna-store",
    displayName: "Hanna's Closet",
    avatarUrl: "https://i.pravatar.cc/120?img=47",
    city: "Addis Ababa",
    subcity: "Kirkos",
    ratingAvg: 4.9,
    ratingCount: 154,
    responseRate: 99,
    responseTime: "within minutes",
    memberSince: "2023-11-02",
    isVerified: true,
    isPremium: true,
  },
];

/** Local browse photos in `public/` â€” every file in each category folder. */
const browsePhotos = {
  phone: [
    "/phone/Screenshot 2026-09-06 144800.png",
    "/phone/Screenshot 2026-09-06 145010.png",
    "/phone/Screenshot 2026-09-06 152241.png",
    "/phone/Screenshot 2026-09-06 222602.png",
    "/phone/Screenshot 2026-09-06 222848.png",
  ],
  vehicle: [
    "/vehicle/Screenshot 2026-09-06 153342.png",
    "/vehicle/Screenshot 2026-09-06 153515.png",
  ],
  furniture: [
    "/Ferniture/Screenshot 2026-09-06 192106.png",
    "/Ferniture/Screenshot 2026-09-06 192323.png",
    "/Ferniture/Screenshot 2026-09-06 223710.png",
    "/Ferniture/Screenshot 2026-09-06 223820.png",
  ],
  electronics: [
    "/elecronics/Screenshot 2026-09-06 152444.png",
    "/elecronics/Screenshot 2026-09-06 152712.png",
    "/elecronics/Screenshot 2026-09-06 221910.png",
    "/elecronics/Screenshot 2026-09-06 222125.png",
    "/elecronics/Screenshot 2026-09-06 222355.png",
  ],
  fashion: [
    "/cloth and shhse/Screenshot 2026-09-06 153703.png",
    "/cloth and shhse/Screenshot 2026-09-06 153856.png",
    "/cloth and shhse/Screenshot 2026-09-06 220729.png",
    "/cloth and shhse/Screenshot 2026-09-06 220913.png",
    "/cloth and shhse/Screenshot 2026-09-06 221116.png",
    "/cloth and shhse/Screenshot 2026-09-06 221648.png",
  ],
  kids: [
    "/kids/Screenshot 2026-09-06 223259.png",
    "/kids/Screenshot 2026-09-06 223423.png",
    "/kids/Screenshot 2026-09-06 223530.png",
  ],
} as const;

function imgs(paths: readonly string[], w = 1200, h = 900) {
  return paths.map((path) => ({
    id: path,
    url: path,
    width: w,
    height: h,
  }));
}

function daysAgo(n: number) {
  return new Date(Date.now() - n * 24 * 60 * 60 * 1000).toISOString();
}

export const listings: Listing[] = [
  {
    id: "l-1001",
    title: "iPhone 13 Pro 256GB â€” Sierra Blue",
    description:
      "Excellent condition, battery health 91%. Comes with original box, charger and a spare case. No cracks, screen protector on since day one. Selling because I upgraded.",
    priceCents: 8500000,
    isNegotiable: true,
    acceptsSwap: false,
    condition: "like_new",
    status: "active",
    categoryId: "cat-phones",
    categoryName: "Phones & Tablets",
    city: "Addis Ababa",
    subcity: "Bole",
    landmark: "Near Edna Mall",
    images: imgs([browsePhotos.phone[0]], 1200, 1200),
    seller: sellers[0]!,
    publishedAt: daysAgo(1),
    viewCount: 214,
    saveCount: 19,
    promotion: "featured",
    attributes: { Brand: "Apple", Model: "iPhone 13 Pro", Storage: "256GB", "Battery health": "91%" },
  },
  {
    id: "l-1002",
    title: "3-Seat Fabric Sofa, Grey",
    description:
      "Comfortable grey fabric sofa, used for about a year. Minor wear on one armrest, otherwise clean and sturdy. Buyer arranges pickup â€” I'm on the 2nd floor, no elevator.",
    priceCents: 1200000,
    isNegotiable: true,
    acceptsSwap: true,
    condition: "good",
    status: "active",
    categoryId: "cat-furniture",
    categoryName: "Furniture",
    city: "Addis Ababa",
    subcity: "Yeka",
    images: imgs([browsePhotos.furniture[0]]),
    seller: sellers[1]!,
    publishedAt: daysAgo(2),
    viewCount: 98,
    saveCount: 7,
    promotion: "homepage",
  },
  {
    id: "l-1003",
    title: "Toyota Vitz 2015, well maintained",
    description:
      "Single owner, full service history at authorized garage. 98,000 km. New tires last month. AC works perfectly. Price is slightly negotiable for serious buyers only.",
    priceCents: 165000000,
    isNegotiable: true,
    acceptsSwap: false,
    condition: "good",
    status: "active",
    categoryId: "cat-vehicles",
    categoryName: "Vehicles",
    city: "Addis Ababa",
    subcity: "Nifas Silk-Lafto",
    images: imgs([browsePhotos.vehicle[0]]),
    seller: sellers[2]!,
    publishedAt: daysAgo(4),
    viewCount: 342,
    saveCount: 41,
    promotion: "urgent",
    attributes: { Year: "2015", Mileage: "98,000 km", Fuel: "Petrol", Transmission: "Manual" },
  },
  {
    id: "l-1004",
    title: "Women's leather handbag, barely used",
    description:
      "Beautiful genuine leather handbag, used twice. Selling because it was a duplicate gift. Comes with dust bag.",
    priceCents: 320000,
    isNegotiable: false,
    acceptsSwap: true,
    condition: "like_new",
    status: "active",
    categoryId: "cat-fashion",
    categoryName: "Fashion",
    city: "Addis Ababa",
    subcity: "Kirkos",
    images: imgs([browsePhotos.fashion[0]], 1000, 1200),
    seller: sellers[3]!,
    publishedAt: daysAgo(1),
    viewCount: 156,
    saveCount: 33,
    promotion: "featured",
  },
  {
    id: "l-1005",
    title: "Dell Latitude Laptop, i5, 8GB RAM",
    description:
      "Reliable office laptop. 256GB SSD, fast boot, good battery (about 4 hours). Light scratches on the lid, screen is flawless. Charger included.",
    priceCents: 2800000,
    isNegotiable: true,
    acceptsSwap: false,
    condition: "good",
    status: "active",
    categoryId: "cat-electronics",
    categoryName: "Electronics",
    city: "Addis Ababa",
    subcity: "Bole",
    images: imgs([browsePhotos.electronics[0]]),
    seller: sellers[0]!,
    publishedAt: daysAgo(6),
    viewCount: 77,
    saveCount: 5,
    promotion: "homepage",
    attributes: { Brand: "Dell", Model: "Latitude 5490", RAM: "8GB", Storage: "256GB SSD" },
  },
  {
    id: "l-1006",
    title: "Kids bicycle, ages 5-8",
    description: "Sturdy kids bike, training wheels included. Outgrown quickly, hardly used.",
    priceCents: 180000,
    isNegotiable: true,
    acceptsSwap: true,
    condition: "good",
    status: "active",
    categoryId: "cat-kids",
    categoryName: "Kids & Baby",
    city: "Addis Ababa",
    subcity: "Lideta",
    images: imgs([browsePhotos.kids[0]], 1100, 1100),
    seller: sellers[1]!,
    publishedAt: daysAgo(3),
    viewCount: 41,
    saveCount: 2,
    promotion: null,
  },
  {
    id: "l-1007",
    title: "Samsung 55'' 4K Smart TV",
    description:
      "Crisp 4K picture, built-in apps (YouTube, Netflix). Wall mount bracket included. Selling due to moving abroad.",
    priceCents: 4200000,
    isNegotiable: false,
    acceptsSwap: false,
    condition: "like_new",
    status: "reserved",
    categoryId: "cat-electronics",
    categoryName: "Electronics",
    city: "Addis Ababa",
    subcity: "Bole",
    images: imgs([browsePhotos.electronics[1]]),
    seller: sellers[0]!,
    publishedAt: daysAgo(5),
    viewCount: 189,
    saveCount: 22,
    promotion: "homepage",
  },
  {
    id: "l-1008",
    title: "Wooden dining table + 4 chairs",
    description: "Solid wood dining set, seats four comfortably. Some scuffs on legs, top is in great shape.",
    priceCents: 950000,
    isNegotiable: true,
    acceptsSwap: false,
    condition: "fair",
    status: "active",
    categoryId: "cat-furniture",
    categoryName: "Furniture",
    city: "Adama",
    subcity: "Adama Ketema",
    images: imgs([browsePhotos.furniture[1]]),
    seller: sellers[2]!,
    publishedAt: daysAgo(9),
    viewCount: 63,
    saveCount: 4,
    promotion: null,
  },
  {
    id: "l-1009",
    title: "Men's running shoes, size 42, new",
    description: "Never worn, wrong size ordered online. Original box included.",
    priceCents: 210000,
    isNegotiable: false,
    acceptsSwap: false,
    condition: "new",
    status: "active",
    categoryId: "cat-fashion",
    categoryName: "Fashion",
    city: "Addis Ababa",
    subcity: "Kirkos",
    images: imgs([browsePhotos.fashion[1]], 1100, 1100),
    seller: sellers[3]!,
    publishedAt: daysAgo(1),
    viewCount: 132,
    saveCount: 26,
    promotion: "urgent",
  },
  {
    id: "l-1010",
    title: "Espresso machine, semi-automatic",
    description: "Makes great espresso and steamed milk. Descaled regularly, works like new.",
    priceCents: 750000,
    isNegotiable: true,
    acceptsSwap: true,
    condition: "good",
    status: "active",
    categoryId: "cat-electronics",
    categoryName: "Electronics",
    city: "Addis Ababa",
    subcity: "Yeka",
    images: imgs([browsePhotos.electronics[2]], 1100, 1100),
    seller: sellers[1]!,
    publishedAt: daysAgo(7),
    viewCount: 54,
    saveCount: 8,
    promotion: null,
  },
  {
    id: "l-1011",
    title: "Guitar, acoustic, with case",
    description: "Great beginner guitar, nice tone, comes with a padded gig bag and extra strings.",
    priceCents: 480000,
    isNegotiable: true,
    acceptsSwap: true,
    condition: "good",
    status: "active",
    categoryId: "cat-furniture",
    categoryName: "Furniture",
    city: "Bahir Dar",
    subcity: "Belay Zeleke",
    images: imgs([browsePhotos.furniture[2]], 1000, 1200),
    seller: sellers[2]!,
    publishedAt: daysAgo(2),
    viewCount: 47,
    saveCount: 6,
    promotion: null,
  },
  {
    id: "l-1012",
    title: "Baby stroller, foldable, all-terrain",
    description: "Sturdy stroller, big wheels handle uneven roads well. Rain cover included.",
    priceCents: 550000,
    isNegotiable: true,
    acceptsSwap: false,
    condition: "good",
    status: "active",
    categoryId: "cat-kids",
    categoryName: "Kids & Baby",
    city: "Addis Ababa",
    subcity: "Bole",
    images: imgs([browsePhotos.kids[1]], 1100, 1100),
    seller: sellers[0]!,
    publishedAt: daysAgo(10),
    viewCount: 39,
    saveCount: 3,
    promotion: "featured",
  },
  {
    id: "l-1013",
    title: "Samsung Galaxy A54, 128GB",
    description: "Clean screen, dual SIM, charger included. Used for a year.",
    priceCents: 3200000,
    isNegotiable: true,
    acceptsSwap: false,
    condition: "good",
    status: "active",
    categoryId: "cat-phones",
    categoryName: "Phones & Tablets",
    city: "Addis Ababa",
    subcity: "Bole",
    images: imgs([browsePhotos.phone[1]], 1200, 1200),
    seller: sellers[0]!,
    publishedAt: daysAgo(2),
    viewCount: 88,
    saveCount: 6,
    promotion: null,
  },
  {
    id: "l-1014",
    title: "iPad 9th generation, 64GB",
    description: "Wi-Fi model, light use, original cable included.",
    priceCents: 4100000,
    isNegotiable: true,
    acceptsSwap: false,
    condition: "like_new",
    status: "active",
    categoryId: "cat-phones",
    categoryName: "Phones & Tablets",
    city: "Addis Ababa",
    subcity: "Yeka",
    images: imgs([browsePhotos.phone[2]], 1200, 1200),
    seller: sellers[1]!,
    publishedAt: daysAgo(3),
    viewCount: 61,
    saveCount: 4,
    promotion: null,
  },
  {
    id: "l-1015",
    title: "Tecno Spark, barely used",
    description: "Bought last month, selling because I upgraded.",
    priceCents: 950000,
    isNegotiable: true,
    acceptsSwap: true,
    condition: "like_new",
    status: "active",
    categoryId: "cat-phones",
    categoryName: "Phones & Tablets",
    city: "Addis Ababa",
    subcity: "Kirkos",
    images: imgs([browsePhotos.phone[3]], 1200, 1200),
    seller: sellers[3]!,
    publishedAt: daysAgo(1),
    viewCount: 44,
    saveCount: 3,
    promotion: "homepage",
  },
  {
    id: "l-1016",
    title: "Google Pixel 6a, unlocked",
    description: "Unlocked, good battery, small scratch on the back.",
    priceCents: 2800000,
    isNegotiable: true,
    acceptsSwap: false,
    condition: "good",
    status: "active",
    categoryId: "cat-phones",
    categoryName: "Phones & Tablets",
    city: "Addis Ababa",
    subcity: "Bole",
    images: imgs([browsePhotos.phone[4]], 1200, 1200),
    seller: sellers[0]!,
    publishedAt: daysAgo(4),
    viewCount: 52,
    saveCount: 5,
    promotion: null,
  },
  {
    id: "l-1017",
    title: "Honda Fit 2012, city car",
    description: "Reliable daily driver, AC works, service records available.",
    priceCents: 98000000,
    isNegotiable: true,
    acceptsSwap: false,
    condition: "good",
    status: "active",
    categoryId: "cat-vehicles",
    categoryName: "Vehicles",
    city: "Addis Ababa",
    subcity: "Bole",
    images: imgs([browsePhotos.vehicle[1]]),
    seller: sellers[2]!,
    publishedAt: daysAgo(5),
    viewCount: 201,
    saveCount: 18,
    promotion: "featured",
  },
  {
    id: "l-1018",
    title: "Office desk, solid wood",
    description: "Spacious work desk, a few marks on the top.",
    priceCents: 620000,
    isNegotiable: true,
    acceptsSwap: false,
    condition: "good",
    status: "active",
    categoryId: "cat-furniture",
    categoryName: "Furniture",
    city: "Addis Ababa",
    subcity: "Bole",
    images: imgs([browsePhotos.furniture[3]]),
    seller: sellers[1]!,
    publishedAt: daysAgo(6),
    viewCount: 29,
    saveCount: 2,
    promotion: null,
  },
  {
    id: "l-1019",
    title: "Bluetooth speaker, loud bass",
    description: "Portable speaker, 10-hour battery, aux and Bluetooth.",
    priceCents: 180000,
    isNegotiable: true,
    acceptsSwap: true,
    condition: "good",
    status: "active",
    categoryId: "cat-electronics",
    categoryName: "Electronics",
    city: "Addis Ababa",
    subcity: "Kirkos",
    images: imgs([browsePhotos.electronics[3]]),
    seller: sellers[3]!,
    publishedAt: daysAgo(2),
    viewCount: 70,
    saveCount: 8,
    promotion: null,
  },
  {
    id: "l-1020",
    title: "Wireless headphones, noise isolating",
    description: "Over-ear, folding, carrying pouch included.",
    priceCents: 240000,
    isNegotiable: true,
    acceptsSwap: false,
    condition: "like_new",
    status: "active",
    categoryId: "cat-electronics",
    categoryName: "Electronics",
    city: "Addis Ababa",
    subcity: "Bole",
    images: imgs([browsePhotos.electronics[4]]),
    seller: sellers[0]!,
    publishedAt: daysAgo(3),
    viewCount: 58,
    saveCount: 7,
    promotion: "urgent",
  },
  {
    id: "l-1021",
    title: "Women's sneakers, size 38",
    description: "Worn a handful of times, very clean.",
    priceCents: 160000,
    isNegotiable: false,
    acceptsSwap: true,
    condition: "like_new",
    status: "active",
    categoryId: "cat-fashion",
    categoryName: "Fashion",
    city: "Addis Ababa",
    subcity: "Yeka",
    images: imgs([browsePhotos.fashion[2]], 1100, 1100),
    seller: sellers[1]!,
    publishedAt: daysAgo(2),
    viewCount: 91,
    saveCount: 12,
    promotion: null,
  },
  {
    id: "l-1022",
    title: "Men's denim jacket, medium",
    description: "Classic fit, no stains, from a smoke-free home.",
    priceCents: 280000,
    isNegotiable: true,
    acceptsSwap: true,
    condition: "good",
    status: "active",
    categoryId: "cat-fashion",
    categoryName: "Fashion",
    city: "Addis Ababa",
    subcity: "Bole",
    images: imgs([browsePhotos.fashion[3]], 1100, 1100),
    seller: sellers[3]!,
    publishedAt: daysAgo(4),
    viewCount: 47,
    saveCount: 5,
    promotion: null,
  },
  {
    id: "l-1023",
    title: "Summer dress, size M",
    description: "Light fabric, worn twice, hanging in the closet.",
    priceCents: 140000,
    isNegotiable: true,
    acceptsSwap: true,
    condition: "like_new",
    status: "active",
    categoryId: "cat-fashion",
    categoryName: "Fashion",
    city: "Addis Ababa",
    subcity: "Kirkos",
    images: imgs([browsePhotos.fashion[4]], 1100, 1100),
    seller: sellers[3]!,
    publishedAt: daysAgo(1),
    viewCount: 103,
    saveCount: 19,
    promotion: "homepage",
  },
  {
    id: "l-1024",
    title: "Kids school shoes, size 32",
    description: "Outgrown, still in good shape.",
    priceCents: 90000,
    isNegotiable: true,
    acceptsSwap: false,
    condition: "good",
    status: "active",
    categoryId: "cat-fashion",
    categoryName: "Fashion",
    city: "Addis Ababa",
    subcity: "Lideta",
    images: imgs([browsePhotos.fashion[5]], 1100, 1100),
    seller: sellers[1]!,
    publishedAt: daysAgo(5),
    viewCount: 22,
    saveCount: 1,
    promotion: null,
  },
  {
    id: "l-1025",
    title: "Toddler ride-on toy",
    description: "Stable wheels, songs still work, selling because we outgrew it.",
    priceCents: 220000,
    isNegotiable: true,
    acceptsSwap: true,
    condition: "good",
    status: "active",
    categoryId: "cat-kids",
    categoryName: "Kids & Baby",
    city: "Addis Ababa",
    subcity: "Bole",
    images: imgs([browsePhotos.kids[2]], 1100, 1100),
    seller: sellers[0]!,
    publishedAt: daysAgo(2),
    viewCount: 35,
    saveCount: 4,
    promotion: null,
  },
];

export const cities = ["Addis Ababa", "Adama", "Hawassa", "Bahir Dar", "Mekelle"] as const;

export const subcitiesByCity: Record<(typeof cities)[number], string[]> = {
  "Addis Ababa": ["Bole", "Yeka", "Kirkos", "Lideta", "Nifas Silk-Lafto", "CMC"],
  Adama: ["Adama Ketema"],
  Hawassa: ["Tabor", "Haik Dar"],
  "Bahir Dar": ["Belay Zeleke", "Fasilo"],
  Mekelle: ["Ayder", "Kedamay Weyane"],
};

export function getCategoryBySlug(slug: string) {
  return categories.find((c) => c.slug === slug) ?? null;
}

export function getListingById(id: string) {
  return listings.find((l) => l.id === id) ?? null;
}

export function getSimilarListings(listing: Listing, limit = 4) {
  return listings
    .filter(
      (l) =>
        l.id !== listing.id &&
        l.categoryId === listing.categoryId &&
        l.city === listing.city &&
        Math.abs(l.priceCents - listing.priceCents) <= listing.priceCents * 0.6
    )
    .slice(0, limit);
}

/** Listings near the same sub-city (then city) as the given item. */
export function getNearbyListings(listing: Listing, limit = 6) {
  const sameSubcity = listings.filter(
    (l) => l.id !== listing.id && l.city === listing.city && l.subcity === listing.subcity
  );
  if (sameSubcity.length >= limit) return sameSubcity.slice(0, limit);

  const sameCity = listings.filter(
    (l) =>
      l.id !== listing.id &&
      l.city === listing.city &&
      !sameSubcity.some((s) => s.id === l.id)
  );
  return [...sameSubcity, ...sameCity].slice(0, limit);
}

export function getSellerOtherListings(sellerId: string, excludeId: string, limit = 4) {
  return listings.filter((l) => l.seller.id === sellerId && l.id !== excludeId).slice(0, limit);
}
